### ISSUE TITLE
AegeusMod v1.0 Roadmap

### ISSUE THREAD

**Issue by Anturity** [Pramire/Aegeus-Modification#1]
- [ ] Discord bot support
- [ ] Change "/ai" to "/apply"
- [ ] Add a "/serverinfo" command
